"""fix circle_joins table

Revision ID: 8a4cce1d04db
Revises: 636d4ddba7af
Create Date: 2020-12-09 18:31:10.963203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4cce1d04db'
down_revision = '636d4ddba7af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle_joins',
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('circle_id', 'student_id')
    )
    op.drop_table('Student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('circle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['circle_id'], ['circles.id'], name='Student_circle_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='Student_student_id_fkey'),
    sa.PrimaryKeyConstraint('circle_id', 'student_id', name='Student_pkey')
    )
    op.drop_table('circle_joins')
    # ### end Alembic commands ###
