"""finished?

Revision ID: 636d4ddba7af
Revises: 1f97e16fbfc3
Create Date: 2020-12-09 18:26:38.096625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636d4ddba7af'
down_revision = '1f97e16fbfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('circle_id', sa.Integer(), nullable=True))
    op.add_column('instructors', sa.Column('cohort_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'instructors', 'circles', ['circle_id'], ['id'])
    op.create_foreign_key(None, 'instructors', 'cohorts', ['cohort_id'], ['id'])
    op.add_column('students', sa.Column('circle_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('cohort_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'circles', ['circle_id'], ['id'])
    op.create_foreign_key(None, 'students', 'cohorts', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'cohort_id')
    op.drop_column('students', 'circle_id')
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_constraint(None, 'instructors', type_='foreignkey')
    op.drop_column('instructors', 'cohort_id')
    op.drop_column('instructors', 'circle_id')
    # ### end Alembic commands ###
